### ISSUE TITLE
Can't locate object method "register" via package "Devel::IPerl::Plugin::Chart::Plotly" at /usr/local/share/perl5/IPerl.pm line 36.

### ISSUE THREAD

**Issue by gitcnd** [pablrod/p5-Devel-IPerl-Plugin-Chart-Plotly#4]
I installed from CPAN, and hit this:-

IPerl->load_plugin('Chart::Plotly');
Can't locate object method "register" via package "Devel::IPerl::Plugin::Chart::Plotly" at /usr/local/share/perl5/IPerl.pm line 36.

As best I can tell - my setup is OK?

use Chart::Plotly::Trace::Scatter;
my $scatter_trace = Chart::Plotly::Trace::Scatter->new( x => [ 1 .. 5 ], y => [ 1 .. 5 ] );
Chart::Plotly::Trace::Scatter=HASH(0x4114428)

This appears to be a bug either in the code, or in the documentation that didn't tell me something I probably needed to do :-)

**Comment by pablrod** [comment]
Thank you for reporting this!!

Well, the `register` method is here: https://github.com/pablrod/p5-Devel-IPerl-Plugin-Chart-Plotly/blob/df3c446a807b97e0909d257d5dcff05836575ad6/lib/Devel/IPerl/Plugin/Chart/Plotly.pm#L70

Maybe the plugin system has changed. What version of [Devel::IPerl](https://github.com/EntropyOrg/p5-Devel-IPerl) do you have?

I'm using Devel::IPerl 0.006. I'm going to upgrade and try to reproduce the issue!

**Comment by gitcnd** [comment]
Suggest you add a note that Chart::Plotly is not related to Chart::Plotly - super confusing to abbreviate your name to be identical to someone elses module...

**Comment by pablrod** [comment]
Now I'm using `Devel::IPerl` `0.009` and I'm still unable to reproduce this. 

I've upgraded both modules, [Chart::Plotly](https://metacpan.org/pod/Chart::Plotly) and [Devel::IPerl::Plugin::Chart::Plotly](https://metacpan.org/pod/Devel::IPerl::Plugin::Chart::Plotly).

Please, try upgrading to the latest version. You can use the [example notebook](https://github.com/pablrod/p5-Devel-IPerl-Plugin-Chart-Plotly/blob/master/examples/PlotlyPlugin.ipynb) (It can be viewed with [nbviewer](http://nbviewer.jupyter.org/github/pablrod/p5-Devel-IPerl-Plugin-Chart-Plotly/blob/master/examples/PlotlyPlugin.ipynb)).

Regarding the naming of modules, I chose that name because it's a plugin to display objects from `Chart::Plotly` module. That is, I thought that using this name could be easy to remember because `Devel::IPerl` plugin load system appends `Devel::IPerl::Plugin`. Thanks to your comment I've seen that other plugins are using a different convention: removing dots from plugin name. Two of them:
* [Devel::IPerl::Plugin::PDLGraphicsGnuplot](https://metacpan.org/pod/Devel::IPerl::Plugin::PDLGraphicsGnuplot)
* [Devel::IPerl::Plugin::ChartClicker](https://metacpan.org/pod/Devel::IPerl::Plugin::ChartClicker)

Where should I add the note? `Devel::IPerl::Plugin::Chart::Plotly` documentation and example? Do you think it's worth changing the name?

**Comment by pablrod** [comment]
I've been able to reproduce this but only without a proper installation of `Devel::IPerl::Plugin::Chart::Plotly`.

So execute this (maybe with sudo):
```bash
cpanm Devel::IPerl::Plugin::Chart::Plotly
```
and after that execute again in your notebook:
```perl
IPerl->load_plugin('Chart::Plotly');
```
and everything should work!

If not, try to execute this in your notebook:
```perl
use Devel::IPerl::Plugin::Chart::Plotly;
```
and paste the output!

**Comment by pablrod** [comment]
I think that the problem it's already solved, but @gitcnd, please, could you try again?

Also, I'll be glad if you share your opinion about the name!

Thank you!

**Comment by gitcnd** [comment]
Maybe if it was added as a dependency/prerequisite, so it always gets installed?  Then nobody can hit this problem, and nobody has to tear hair trying to work out how to install it?

I think there's sufficiently few users, that it's probably safe to expect 100% of them are going to want this installed.

**Comment by pablrod** [comment]
Unfortunately adding `Chart::Plotly`as a dependency/prerequisite it's not an option because that would introduce a circular dependency between `Devel::IPerl::Plugin::Chart::Plotly` and `Chart::Plotly`.

What do you think about distributing `Devel::IPerl::Plugin::Chart::Plotly` as part of `Chart::Plotly` itself?

**Comment by pablrod** [comment]
I'm going to ship this plugin with [Chart::Plotly](https://metacpan.org/pod/Chart::Plotly). So the next version of this package will be empty. Only to keep backwards compatibility.

I think this way it's easier for users.

**Comment by pablrod** [comment]
With the release [0.033](https://github.com/pablrod/p5-Chart-Plotly/releases/tag/v0.033) of [Chart::Plotly](https://metacpan.org/pod/Chart::Plotly) this plugin now is bundled with the main distribution so this won't happen again
